### ISSUE TITLE
Building LuCi to run on my host machine fails

### ISSUE THREAD

**Issue by jow-** [openwrt/luci#111]
**Reported by reporter on 15 Mar 2010 09:02 UTC**
Here's what I do:
  svn co http://svn.luci.subsignal.org/luci/trunk luci
  # (currently I get revision 5821)
  cd luci
  make
And I get the following error:
  make[Entering directory `/home/ben/dev/svn/luci-trunk/libs/luanet/src'
  cc -O2 -fPIC -I/usr/include/lua5.1   --std=gnu99 -c  ifconfig.c -o ifconfig.o
  cc -O2 -fPIC -I/usr/include/lua5.1   --std=gnu99 -c  bridge.c -o bridge.o
  cc -O2 -fPIC -I/usr/include/lua5.1   --std=gnu99 -c  iwconfig.c -o iwconfig.o
  iwconfig.c: In function iwc_get:
  iwconfig.c:192: error: KILO undeclared (first use in this function)
  iwconfig.c:192: error: (Each undeclared identifier is reported only once
  iwconfig.c:192: error: for each function it appears in.)
  iwconfig.c: In function print_scanning_token:
  iwconfig.c:533: warning: implicit declaration of function iw_saether_ntop
  iwconfig.c:533: warning: passing argument 3 of add_table_entry makes pointer from integer without a cast
  helper.h:28: note: expected const char * but argument is of type int
  iwconfig.c: In function iwc_scan:
  iwconfig.c:653: error: IW_EV_LCP_PK2_LEN undeclared (first use in this function)
  iwconfig.c:653: error: IW_EV_POINT_PK2_LEN undeclared (first use in this function)
  make[2](2]:): *** [Error 1
  make[2](iwconfig.o]): Leaving directory`/home/ben/dev/svn/luci-trunk/libs/luanet/src'
  make[**\* [compile](1]:) Error 2
  make[Leaving directory `/home/ben/dev/svn/luci-trunk/libs/luanet'
  **\* Compilation of libs/luanet failed!
  make: **\* [gccbuild](1]:) Error 1

Everything works fine with version 0.8.8 however:
  svn co http://svn.luci.subsignal.org/luci/tags/0.8.8 luci-0.8.8
  cd luci-0.8.8
  make runhttpd
  # and I can connect to http://localhost:8080/luci
## 

Benot Knecht
